# 类别路径映射配置
# 定义不同类别对应的文件夹路径

# 工作相关
工作: "工作文档"
个人: "个人文档"
财务: "财务文档"
其他: "其他文档"

# 项目相关
项目A: "项目/项目A"
项目B: "项目/项目B"
项目C: "项目/项目C"

# 客户相关
客户A: "客户/客户A"
客户B: "客户/客户B"

# 文档类型
合同: "合同文档"
发票: "发票文档"
报告: "报告文档"
会议记录: "会议记录"
培训材料: "培训材料"

# 特殊类别
重要: "重要文件"
归档: "归档文件"
待审核: "待审核"
待整理: "待整理"
