# 基于LLM和向量数据库的自动文档分类系统配置文件

# LLM配置
llm:
  provider: "ollama"  # openai, claude, ollama
  model: "qwen3"  # For Ollama: llama3.2:1b, qwen3, etc.
  api_key: "ollama"  # Ollama不需要真实API密钥，但这里设置一个占位符
  base_url: "http://localhost:11434"  # Ollama default endpoint
  temperature: 0.1
  max_tokens: 1000

# Ollama配置 - 用于文档阅读和分类
ollama:
  base_url: "http://localhost:11434"
  model: "qwen3"  # 文档阅读和分类模型
  reader_model: "qwen3"  # 专用阅读模型（可选）
  classifier_model: "qwen3"  # 专用分类模型（可选）
  timeout: 300
  max_retries: 3
  enable_reader: true  # 是否启用Ollama文档阅读
  enable_insights: true  # 是否提取文档洞察
  context_window: 4096  # 模型上下文窗口大小

# 嵌入模型配置
embedding:
  type: "local"  # local, api
  model_name: "BAAI/bge-m3"  # bge-m3, e5-large, openai-ada
  device: "auto"  # auto, cpu, cuda
  max_length: 8192
  dimension: 1024
  batch_size: 32
  max_workers: 4
  chunk_strategy: "smart"  # smart, fixed, none
  fallback_strategy: "retry"  # retry, skip, alternative
  
  # 本地模型配置
  local:
    model_path: null  # 自定义模型路径，null表示使用预训练模型
    cache_dir: ".ods/models"
    
  # API模型配置
  api:
    provider: "openai"  # openai, anthropic
    api_key: null  # 请设置您的API密钥
    api_base: null  # 自定义API端点
    timeout: 30
    retry_attempts: 3

# 数据库配置
database:
  type: "sqlite"
  path: ".ods/db.sqlite"
  vector_db_path: ".ods/vector_db"
  sqlite_path: "data/audit.db"
  audit_table: "file_operations"
  status_table: "file_status"

# 向量存储配置
vector_store:
  chroma_path: "data/chroma_db"
  collection_name: "documents"
  similarity_threshold: 0.8
  max_results: 10

# LlamaIndex配置
llama_index:
  enable: true
  index_path: "data/llama_index"
  chunk_size: 1000
  chunk_overlap: 200
  similarity_top_k: 5

# 分类配置 - 支持多标签分类
classification:
  # 置信度阈值配置
  confidence_threshold:
    auto: 0.85      # 自动分类阈值
    review: 0.6     # 需要审核的阈值
    min: 0.3        # 最低置信度
  
  # 标签体系定义 - 支持多维度分类
  taxonomies:
    主类别:          # 主要分类维度
      - "工作"
      - "个人" 
      - "财务"
      - "其他"
    文档类型:        # 文档性质维度
      - "报告"
      - "合同"
      - "发票"
      - "照片"
      - "计划"
      - "会议记录"
    敏感级别:        # 安全级别维度
      - "公开"
      - "内部"
      - "机密"
  
  # 标签规则配置
  tag_rules:
    max_tags_per_file: 5        # 每个文件最多标签数
    primary_tag_required: true  # 是否必须指定主标签
    allow_cross_categories: true # 是否允许跨类别标签
    
    # 互斥标签组（不能同时出现）
    mutually_exclusive:
      - ["个人", "工作"]
      - ["公开", "机密"]
    
    # 标签优先级（用于确定主标签）
    priority_order:
      - "主类别"
      - "文档类型" 
      - "敏感级别"

# 文件处理配置
file:
  source_directory: "D:\\OneDrive"  # 请设置您的源目录
  target_directory: "D:\\OneDrive"
  supported_extensions:
    - ".pdf"
    - ".docx"
    - ".doc"
    - ".pptx"
    - ".ppt"
    - ".txt"
    - ".md"
    - ".jpg"
    - ".jpeg"
    - ".png"
  max_file_size: 524288000  # 500MB

# 规则引擎配置 - 支持自动标签和分类
rules:
  # 预分类规则（在LLM分类前执行）
  pre_classification:
    - name: "发票文件自动标签"
      condition: "filename_contains"
      value: "发票"
      action: "add_tag"
      target: "发票"
      priority: "high"
      
    - name: "合同文件自动标签"
      condition: "filename_contains" 
      value: "合同"
      action: "add_tag"
      target: "合同"
      priority: "high"
      
    - name: "排除临时文件"
      condition: "file_extension"
      value: ["tmp", "log", "bak"]
      action: "exclude"
      priority: "high"
  
  # 后分类规则（在LLM分类后执行）
  post_classification:
    - name: "机密文件特殊处理"
      condition: "tags_contain"
      value: "机密"
      action: "require_review"
      priority: "high"
      
    - name: "财务文件路径调整"
      condition: "tags_contain"
      value: "财务"
      action: "set_path_template"
      template: "财务/{{year}}/{{month}}/{{filename}}"
      priority: "medium"



# 文本处理配置
text_processing:
  max_chunk_size: 1000
  overlap_size: 100
  min_chunk_size: 100
  clean_text: true
  remove_stopwords: false
  lemmatize: false
  generate_summary: true
  extract_keywords: true
  max_summary_length: 200
  max_keywords: 10

# 解析器配置
parser:
  priority:
    - "pdf"
    - "office"
    - "text"
    - "ocr"
  ocr_fallback: true

# PDF解析配置
pdf:
  max_pages: 100
  extract_metadata: true

# Office文档解析配置
office:
  extract_metadata: true
  max_slides: 50  # PowerPoint最大幻灯片数
  max_sheets: 10  # Excel最大工作表数

# 文本文件解析配置
text:
  max_length: 1000000  # 1MB
  encoding_detection: true
  default_encoding: "utf-8"

# OCR配置
ocr:
  language: "chi_sim+eng"  # 中文简体+英文
  psm: 3  # Page Segmentation Mode
  oem: 3  # OCR Engine Mode
  dpi: 300
  min_confidence: 30
  preprocess: true
  resize_factor: 2.0

# 文件监控配置
watcher:
  enabled: true  # 是否启用文件监控功能
  check_interval: 5  # 文件变化检测间隔（秒）
  debounce_time: 2  # 文件稳定等待时间（秒），避免处理正在写入的文件
  max_queue_size: 100  # 待处理文件队列最大长度
  processed_cache_size: 1000  # 已处理文件缓存大小，用于避免重复处理
  recursive: true  # 是否递归监控子目录

  # 文件过滤配置
  file_filters:
    extensions: []  # 要监控的文件扩展名，为空则监控所有支持的格式
    exclude_patterns: []  # 排除的文件名模式（支持正则表达式）
    min_size: 0  # 最小文件大小（字节）
    max_size: 104857600  # 最大文件大小（字节），默认100MB

  # 监控策略配置
  strategy:
    immediate_process: false  # 是否立即处理文件变化
    batch_process: true  # 是否批量处理多个文件
    batch_size: 5  # 批量处理大小
    process_existing: false  # 启动时是否处理已存在的文件

  # 监控目录配置
  directories:
    - path: ""  # 监控目录路径，为空则使用file.source_directory
      recursive: true
      filters: []

# 路径规划配置
path_planning:
  base_path: "D:\\OneDrive"
  default_categories: ["工作", "个人", "财务", "其他"]
  multi_label_strategy: "primary_with_links"
  path_template: "{category}/{year}/{month}"
  conflict_resolution: "suffix"
  max_path_length: 260
  category_mapping_file: "config/category_mapping.yaml"
  special_paths:
    uncategorized: "待整理"
    needs_review: "待审核"
    important: "重要文件"
    archive: "归档"

# 命名生成配置（扩展）
naming:
  # 基础配置
  max_filename_length: 200
  enable_llm_title: true
  title_max_length: 50
  conflict_resolution: "suffix"
  invalid_chars: "[<>:\"/\\\\|?*]"
  replacement_char: "_"
  templates_file: "config/naming_templates.yaml"
  
  # 多标签命名模板
  default_template: "{{主类别}}/{{文档类型}}/{{title|default(original_name)}}.{{ext}}"
  
  # 分类别命名模板
  category_templates:
    财务:
      template: "{{主类别}}/财务/{{year}}/{{month}}/{{title|default(original_name)}}.{{ext}}"
    工作:
      template: "{{主类别}}/工作/{{文档类型}}/{{title|default(original_name)}}.{{ext}}"
    个人:
      template: "{{主类别}}/个人/{{year}}/{{title|default(original_name)}}.{{ext}}"
  
  # 特殊标签命名规则
  special_rules:
    - condition: "tags_contain"
      value: "机密"
      suffix: "[机密]"
    - condition: "tags_contain"
      value: "发票"
      prefix: "发票-"
    - condition: "file_size > 10485760"  # 10MB
      suffix: "[大文件]"

# 系统配置
system:
  log_level: "INFO"
  log_file: ".ods/ods.log"
  temp_directory: ".ods/temp"
  backup_enabled: true
  dry_run: false
